CREATE DATABASE IF NOT EXISTS kusakari_e2e
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, DROP, INDEX, REFERENCES
  ON kusakari_e2e.* TO 'kusakari'@'%';

FLUSH PRIVILEGES;
